FILTER_TYPE_DICT = {
    "event_date": "agDateColumnFilter",
    "hvfhs_license_num": "agTextColumnFilter",
    "dispatching_base_num": "agSetColumnFilter",
    "originating_base_num": "agSetColumnFilter",
    "request_datetime": "",
    "on_scene_datetime": "",
    "pickup_datetime": "",
    "dropoff_datetime": "",
    "PULocationID": "agSetColumnFilter",
    "DOLocationID": "agSetColumnFilter",
    "trip_miles": "agNumberColumnFilter",
    "trip_time": "agNumberColumnFilter",
    "base_passenger_fare": "agNumberColumnFilter",
    "tolls": "agNumberColumnFilter",
    "bcf": "agNumberColumnFilter",
    "sales_tax": "agNumberColumnFilter",
    "congestion_surcharge": "agNumberColumnFilter",
    "airport_fee": "agNumberColumnFilter",
    "tips": "agNumberColumnFilter",
    "driver_pay": "agNumberColumnFilter",
    "shared_request_flag": "agSetColumnFilter",
    "shared_match_flag": "agSetColumnFilter",
    "access_a_ride_flag": "agSetColumnFilter",
    "wav_request_flag": "agSetColumnFilter",
    "wav_match_flag": "agSetColumnFilter",
}

VISIBLE_COLUMNS = [
    "dispatching_base_num",
    "originating_base_num",
    "PULocationID",
    "DOLocationID",
    "trip_miles",
    "trip_time",
    "driver_pay",
    "tips",
]
